### PR TITLE
Adding Spanish translation, minor fixes and comments in English

### PR DESCRIPTION
**Pull request by IlDucci**
- English texts:
  - Added tips for future translators. Please check them out.
  - Fixed a missing uppercase on "Click finish to exit the Setup Tool."
  - Fixed a typo at NoComponentsSelected.

- Spanish:
  - Added a new translation. Still have to see if I can put in this script strings from the original Inno Setup texts, in case this file could supersede the original ones.
  - @nipkownix , you told me to check this file: https://github.com/nipkownix/SH2EE-web-installer/blob/master/resources/license.rtf , but there is no Portuguese equivalent that I could use to add the Spanish version. Where can I find this?

### CODE REVIEW

**Comment by nipkownix** [comment]
>but there is no Portuguese equivalent that I could use to add the Spanish version. Where can I find this?

Ah, sorry about that.
I was slacking a bit, tbh, as I hate dealing with .rtf text files, but I've just pushed the pt-br license as an example.

>Still have to see if I can put in this script strings from the original Inno Setup texts, in case this file could supersede the original ones.

If you have the replacements in the ``[Messages]`` section, they should supersede the originals, yeah. But it shouldn't be needed, unless the original Spanish Inno Setup has translation issues.

**Comment by IlDucci** [comment]
That was a bit of a curveball for me, having to fix the conflict. Please check if I did everything alright there.

**Comment by nipkownix** [comment]
Ah, sorry about that. Git can be annoying sometimes.
Everything looks good, though. Many thanks for the improvements and translation!

Edit: Little preview (in case you haven't compiled the installer yourself yet):
image

**Comment by IlDucci** [comment]
You're welcome. And thanks for that screenshot. Seems like the first line was untranslated... Where was it?

**Comment by nipkownix** [comment]
Ah, I probably forgot to add that to the custom texts. Oops.
I'll add those soon. Nice catch!

**Comment by nipkownix** [comment]
Added in 1cc7c25.

**Pull request merged**
