### PR TITLE
Spanish corrections for original Inno Setup strings

### PR DESCRIPTION
**Pull request by IlDucci**
Minor proofediting regarding the existing Spanish translations of Inno Setup's download plugin. I do have a bone to pick with the Setup's translation, but since it's packed inside a .zip file, I do not know where should I put it.

### CODE REVIEW

**Comment by nipkownix** [comment]
Oh hey! Thanks for the initiative, but there are some concerns here.
Even if we merge this, the installer only supports English at the moment. Everything is hardcoded to use English strings.
If we had interest in adding more languages, and people to do the proper translations, I would gladly add the proper support for them, but it doesn't look like that's the case at the moment.

Perhaps asking about this in the SH2 EE git repo would bring attention to more people, and raise the chances of it happening.

**Comment by IlDucci** [comment]
The main reason why I did this on your repo, rather than on SH2EE's, was because of being linked via GitHub. Should I try to send the changes there?

I was also going to try adding the multilanguage support to the installer. And the installer was just released, so not so many people would show their interest on having it translated yet...

**Comment by nipkownix** [comment]
> Should I try to send the changes there?

No, sending them here is fine, as this is a submodule from the main SH2EE repo.

>I was also going to try adding the multilanguage support to the installer

Nice! But please hold on and don't do it just yet, because I'll add  proper support for .iss lang files soon, to make everything easier.

Thank you!

**Comment by IlDucci** [comment]
> Nice! But please hold on and don't do it just yet, because I'll add proper support for .iss lang files soon, to make everything easier.

Okay then! If you are going to do it, I will wait for you. If you need any testing or suggestions (my ISS coding skills are probably lower than yours), feel free to tag me around here.

**Comment by nipkownix** [comment]
@IlDucci, the latest commits added multi-language support.

See here:
https://github.com/nipkownix/SH2EE-web-installer/tree/master/languages

You might also want to edit this:
https://github.com/nipkownix/SH2EE-web-installer/blob/master/resources/license.rtf

**Comment by IlDucci** [comment]
Thank you! I'll get with it right away.

**Pull request merged**
