### PR TITLE
Translated Lines Needed DONE!

### PR DESCRIPTION
**Pull request by lucazandrade**
It's done, I don't know if I did it right, I think I was doing it wrong, but I believe I got it now... I don't know much about github, but I believe I'm learning, I hope it's correct.

### CODE REVIEW

**Comment by nipkownix** [comment]
Cool, thanks. Seems this is missing a couple of lines, though. Is this intentional?

**Comment by lucazandrade** [comment]
> Cool, thanks. Seems this is missing a couple of lines, though. Is this intentional?

No, I didn't delete any lines...
Did I miss something?

**Comment by nipkownix** [comment]
I meant there are a couple more lines that need translation, as mentioned in #19 :p

**Comment by lucazandrade** [comment]
Sorry about that, I believe this was the missing line.

**Comment by nipkownix** [comment]
Thanks again!

**Pull request merged**
